import type { AppItem, Hub, TickerMessage, PersonalityFigure } from "@/types";

// ─── App Grid (4 rows × 4 cols = 16 items) ─────────────────────────────────
export const APP_GRID_ROW1: AppItem[] = [
  { id: "google", name: "Google", nameUrdu: "گوگل", icon: "🔍", url: "https://www.google.com", color: "#4285f4" },
  { id: "youtube", name: "YouTube", nameUrdu: "یوٹیوب", icon: "▶️", url: "https://www.youtube.com", color: "#ff0000" },
  { id: "whatsapp", name: "WhatsApp", nameUrdu: "واٹس ایپ", icon: "💬", url: "https://web.whatsapp.com", color: "#25d366" },
  { id: "facebook", name: "Facebook", nameUrdu: "فیس بک", icon: "👤", url: "https://www.facebook.com", color: "#1877f2" },
];

export const APP_GRID_ROW2: AppItem[] = [
  { id: "gmail", name: "Gmail", nameUrdu: "جی میل", icon: "📧", url: "https://mail.google.com", color: "#ea4335" },
  { id: "maps", name: "Maps", nameUrdu: "نقشہ", icon: "🗺️", url: "https://maps.google.com", color: "#34a853" },
  { id: "news", name: "News", nameUrdu: "خبریں", icon: "📰", url: "https://news.google.com", color: "#4285f4" },
  { id: "translate", name: "Translate", nameUrdu: "ترجمہ", icon: "🌐", url: "https://translate.google.com", color: "#4285f4" },
];

export const APP_GRID_ROW3: AppItem[] = [
  { id: "chatgpt", name: "ChatGPT", nameUrdu: "چیٹ جی پی ٹی", icon: "🤖", url: "https://chat.openai.com", color: "#00a67e" },
  { id: "twitter", name: "Twitter", nameUrdu: "ٹویٹر", icon: "🐦", url: "https://twitter.com", color: "#1da1f2" },
  { id: "instagram", name: "Instagram", nameUrdu: "انسٹاگرام", icon: "📸", url: "https://www.instagram.com", color: "#e1306c" },
  { id: "amazon", name: "Amazon", nameUrdu: "امازون", icon: "🛒", url: "https://www.amazon.com", color: "#ff9900" },
];

export const APP_GRID_ROW4: AppItem[] = [
  { id: "wikipedia", name: "Wikipedia", nameUrdu: "ویکیپیڈیا", icon: "📚", url: "https://www.wikipedia.org", color: "#fff" },
  { id: "reddit", name: "Reddit", nameUrdu: "ریڈٹ", icon: "🟠", url: "https://www.reddit.com", color: "#ff4500" },
  { id: "tiktok", name: "TikTok", nameUrdu: "ٹک ٹاک", icon: "🎵", url: "https://www.tiktok.com", color: "#000" },
  { id: "netflix", name: "Netflix", nameUrdu: "نیٹ فلکس", icon: "🎬", url: "https://www.netflix.com", color: "#e50914" },
];

// ─── Content Hubs ───────────────────────────────────────────────────────────
export const HUBS: Hub[] = [
  {
    id: "islamic",
    name: "Islamic",
    nameUrdu: "اسلامی",
    icon: "☪️",
    color: "#00cc66",
    apps: [
      { id: "quran", name: "Quran.com", nameUrdu: "قرآن", icon: "📖", url: "https://quran.com", color: "#00cc66" },
      { id: "islamicfinder", name: "IslamicFinder", nameUrdu: "اسلامک فائنڈر", icon: "🕌", url: "https://www.islamicfinder.org", color: "#2d8a4e" },
      { id: "sunnah", name: "Sunnah.com", nameUrdu: "سنت", icon: "📜", url: "https://sunnah.com", color: "#1a5c35" },
      { id: "duas", name: "Duas.org", nameUrdu: "دعائیں", icon: "🤲", url: "https://duas.org", color: "#00a855" },
      { id: "islamqa", name: "IslamQA", nameUrdu: "اسلام سوال", icon: "❓", url: "https://islamqa.info", color: "#006633" },
      { id: "makkah", name: "Makkah Live", nameUrdu: "مکہ لائیو", icon: "🕋", url: "https://www.youtube.com/watch?v=_eeIv0NGIXM", color: "#c8a000" },
      { id: "aladhan", name: "Aladhan", nameUrdu: "اوقات نماز", icon: "🕐", url: "https://aladhan.com", color: "#33aa77" },
      { id: "nida_e_haq", name: "Nida-e-Haq", nameUrdu: "ندائے حق", icon: "📻", url: "https://www.youtube.com/@NidaEHaq", color: "#009944" },
      { id: "iqra_tv", name: "Iqra TV", nameUrdu: "اقرا ٹی وی", icon: "📺", url: "https://www.iqratv.pk", color: "#00aa55" },
      { id: "hamariweb", name: "HamariWeb Islamic", nameUrdu: "ہماری ویب", icon: "🌙", url: "https://hamariweb.com/islam/", color: "#007744" },
      { id: "mutahhir", name: "Mutahhir", nameUrdu: "مطہر", icon: "🔊", url: "https://www.youtube.com/@Mutahirislam", color: "#005533" },
      { id: "islamicvideos", name: "Islamic Videos", nameUrdu: "اسلامی ویڈیوز", icon: "🎥", url: "https://www.youtube.com/results?search_query=islamic+videos", color: "#228855" },
      { id: "al_jazeera_arabic", name: "Al Jazeera Arabic", nameUrdu: "الجزیرہ عربی", icon: "📡", url: "https://www.aljazeera.net", color: "#cc8800" },
      { id: "darussalam", name: "Darussalam", nameUrdu: "دارالسلام", icon: "🏛️", url: "https://darussalam.com", color: "#004422" },
      { id: "masnoonduaas", name: "Masnoon Duas", nameUrdu: "مسنون دعائیں", icon: "🌟", url: "https://duas.org/category/masnoon-duaas", color: "#33cc88" },
      { id: "calligraph", name: "Arabic Calligraphy", nameUrdu: "عربی خطاطی", icon: "✒️", url: "https://www.youtube.com/results?search_query=arabic+calligraphy", color: "#aa6600" },
      { id: "tahfiz", name: "Tahfiz Online", nameUrdu: "تحفیظ آن لائن", icon: "📝", url: "https://quran.com/audio", color: "#00bb55" },
      { id: "ramadan", name: "Ramadan Guide", nameUrdu: "رمضان گائیڈ", icon: "🌙", url: "https://www.islamicfinder.org/ramadan/", color: "#cc9900" },
      { id: "zakatonline", name: "Zakat Calc", nameUrdu: "زکات کیلکولیٹر", icon: "💰", url: "https://www.islamicfinder.org/zakat-calculator/", color: "#009933" },
      { id: "hajj", name: "Hajj Guide", nameUrdu: "حج گائیڈ", icon: "🕋", url: "https://www.islamicfinder.org/hajj-guide/", color: "#bb7700" },
    ],
  },
  {
    id: "news",
    name: "News",
    nameUrdu: "خبریں",
    icon: "📰",
    color: "#4285f4",
    apps: [
      { id: "geo", name: "Geo News", nameUrdu: "جیو نیوز", icon: "📺", url: "https://www.geo.tv", color: "#cc0000" },
      { id: "ard", name: "ARY News", nameUrdu: "اے آر وائی", icon: "📡", url: "https://arynews.tv", color: "#0055aa" },
      { id: "bbc", name: "BBC News", nameUrdu: "بی بی سی", icon: "🌍", url: "https://www.bbc.com/news", color: "#bb1919" },
      { id: "dawn", name: "Dawn", nameUrdu: "ڈان", icon: "🗞️", url: "https://www.dawn.com", color: "#c8372d" },
      { id: "express", name: "Express Tribune", nameUrdu: "ایکسپریس", icon: "📰", url: "https://tribune.com.pk", color: "#cd3333" },
      { id: "aljazeera", name: "Al Jazeera", nameUrdu: "الجزیرہ", icon: "🎙️", url: "https://www.aljazeera.com", color: "#cc8800" },
      { id: "cnn", name: "CNN", nameUrdu: "سی این این", icon: "📻", url: "https://www.cnn.com", color: "#cc0000" },
      { id: "reuters", name: "Reuters", nameUrdu: "رائٹرز", icon: "🌐", url: "https://www.reuters.com", color: "#ff8000" },
      { id: "jang", name: "Jang", nameUrdu: "جنگ", icon: "📄", url: "https://jang.com.pk", color: "#006600" },
      { id: "nawaiwaqt", name: "Nawa-i-Waqt", nameUrdu: "نوائے وقت", icon: "📋", url: "https://www.nawaiwaqt.com.pk", color: "#990000" },
      { id: "tribune", name: "Tribune", nameUrdu: "ٹریبیون", icon: "🗒️", url: "https://tribune.com.pk", color: "#cc2200" },
      { id: "samaa", name: "Samaa News", nameUrdu: "سما نیوز", icon: "📱", url: "https://www.samaa.tv", color: "#0066cc" },
      { id: "dunya", name: "Dunya News", nameUrdu: "دنیا نیوز", icon: "🖥️", url: "https://dunyanews.tv", color: "#003399" },
      { id: "bbcurdu", name: "BBC Urdu", nameUrdu: "بی بی سی اردو", icon: "🔊", url: "https://www.bbc.com/urdu", color: "#990000" },
      { id: "voaurdu", name: "VOA Urdu", nameUrdu: "وی او اے اردو", icon: "📢", url: "https://www.urduvoa.com", color: "#003366" },
      { id: "radio", name: "Radio Pakistan", nameUrdu: "ریڈیو پاکستان", icon: "📻", url: "https://www.radio.gov.pk", color: "#006600" },
      { id: "apnews", name: "AP News", nameUrdu: "اے پی نیوز", icon: "🌍", url: "https://apnews.com", color: "#cc0000" },
      { id: "guardian", name: "The Guardian", nameUrdu: "گارڈین", icon: "🌿", url: "https://www.theguardian.com", color: "#005689" },
      { id: "indep", name: "Independent", nameUrdu: "انڈیپنڈنٹ", icon: "📃", url: "https://www.independent.co.uk", color: "#e31f26" },
      { id: "thehill", name: "The Hill", nameUrdu: "دی ہل", icon: "🏛️", url: "https://thehill.com", color: "#005b99" },
    ],
  },
  {
    id: "ai",
    name: "AI Tools",
    nameUrdu: "اے آئی",
    icon: "🤖",
    color: "#00a67e",
    apps: [
      { id: "chatgpt2", name: "ChatGPT", nameUrdu: "چیٹ جی پی ٹی", icon: "💬", url: "https://chat.openai.com", color: "#00a67e" },
      { id: "gemini", name: "Gemini", nameUrdu: "جیمنی", icon: "✨", url: "https://gemini.google.com", color: "#4285f4" },
      { id: "copilot", name: "Copilot", nameUrdu: "کوپائلٹ", icon: "🔮", url: "https://copilot.microsoft.com", color: "#0078d4" },
      { id: "claude", name: "Claude", nameUrdu: "کلاڈ", icon: "🧠", url: "https://claude.ai", color: "#d97706" },
      { id: "perplexity", name: "Perplexity", nameUrdu: "پرپلیکسٹی", icon: "🔍", url: "https://www.perplexity.ai", color: "#20b2aa" },
      { id: "midjourney", name: "Midjourney", nameUrdu: "مڈجرنی", icon: "🎨", url: "https://www.midjourney.com", color: "#000080" },
      { id: "dalle", name: "DALL-E", nameUrdu: "ڈال ای", icon: "🖼️", url: "https://labs.openai.com", color: "#412991" },
      { id: "stable", name: "Stable Diffusion", nameUrdu: "اسٹیبل ڈفیوژن", icon: "🎭", url: "https://stability.ai", color: "#7c3aed" },
      { id: "grok", name: "Grok", nameUrdu: "گروک", icon: "⚡", url: "https://grok.x.ai", color: "#1da1f2" },
      { id: "poe", name: "Poe", nameUrdu: "پو", icon: "🤖", url: "https://poe.com", color: "#6366f1" },
      { id: "huggingface", name: "HuggingFace", nameUrdu: "ہگنگ فیس", icon: "🤗", url: "https://huggingface.co", color: "#ffd21e" },
      { id: "runway", name: "Runway ML", nameUrdu: "رن وے", icon: "🎬", url: "https://runwayml.com", color: "#000000" },
      { id: "elevenlabs", name: "ElevenLabs", nameUrdu: "الیون لیبز", icon: "🎙️", url: "https://elevenlabs.io", color: "#2563eb" },
      { id: "gamma", name: "Gamma", nameUrdu: "گاما", icon: "📊", url: "https://gamma.app", color: "#7c3aed" },
      { id: "notion_ai", name: "Notion AI", nameUrdu: "نوشن اے آئی", icon: "📝", url: "https://www.notion.so", color: "#000000" },
      { id: "writesonic", name: "Writesonic", nameUrdu: "رائٹ سونک", icon: "✍️", url: "https://writesonic.com", color: "#5c6bc0" },
      { id: "jasper", name: "Jasper", nameUrdu: "جاسپر", icon: "🚀", url: "https://www.jasper.ai", color: "#ef4444" },
      { id: "copy", name: "Copy.ai", nameUrdu: "کاپی اے آئی", icon: "📋", url: "https://www.copy.ai", color: "#8b5cf6" },
      { id: "synthesia", name: "Synthesia", nameUrdu: "سنتھیسیا", icon: "👤", url: "https://www.synthesia.io", color: "#0ea5e9" },
      { id: "heygen", name: "HeyGen", nameUrdu: "ہے جن", icon: "🎥", url: "https://www.heygen.com", color: "#8b5cf6" },
    ],
  },
  {
    id: "social",
    name: "Social",
    nameUrdu: "سوشل",
    icon: "🌐",
    color: "#e1306c",
    apps: [
      { id: "fb", name: "Facebook", nameUrdu: "فیس بک", icon: "👍", url: "https://www.facebook.com", color: "#1877f2" },
      { id: "ig", name: "Instagram", nameUrdu: "انسٹاگرام", icon: "📸", url: "https://www.instagram.com", color: "#e1306c" },
      { id: "tw", name: "Twitter/X", nameUrdu: "ٹویٹر", icon: "🐦", url: "https://twitter.com", color: "#000000" },
      { id: "tt", name: "TikTok", nameUrdu: "ٹک ٹاک", icon: "🎵", url: "https://www.tiktok.com", color: "#000000" },
      { id: "wa", name: "WhatsApp", nameUrdu: "واٹس ایپ", icon: "💬", url: "https://web.whatsapp.com", color: "#25d366" },
      { id: "tg", name: "Telegram", nameUrdu: "ٹیلیگرام", icon: "✈️", url: "https://web.telegram.org", color: "#0088cc" },
      { id: "yt", name: "YouTube", nameUrdu: "یوٹیوب", icon: "▶️", url: "https://www.youtube.com", color: "#ff0000" },
      { id: "ln", name: "LinkedIn", nameUrdu: "لنکڈ ان", icon: "💼", url: "https://www.linkedin.com", color: "#0a66c2" },
      { id: "snap", name: "Snapchat", nameUrdu: "سنیپ چیٹ", icon: "👻", url: "https://web.snapchat.com", color: "#fffc00" },
      { id: "pin", name: "Pinterest", nameUrdu: "پنٹریسٹ", icon: "📌", url: "https://www.pinterest.com", color: "#bd081c" },
      { id: "disc", name: "Discord", nameUrdu: "ڈسکورڈ", icon: "🎮", url: "https://discord.com/app", color: "#5865f2" },
      { id: "twitch", name: "Twitch", nameUrdu: "ٹوچ", icon: "🎯", url: "https://www.twitch.tv", color: "#9146ff" },
      { id: "reddit2", name: "Reddit", nameUrdu: "ریڈٹ", icon: "🟠", url: "https://www.reddit.com", color: "#ff4500" },
      { id: "tumblr", name: "Tumblr", nameUrdu: "ٹمبلر", icon: "📝", url: "https://www.tumblr.com", color: "#35465c" },
      { id: "quora", name: "Quora", nameUrdu: "قوورا", icon: "❓", url: "https://www.quora.com", color: "#aa2200" },
      { id: "medium", name: "Medium", nameUrdu: "میڈیم", icon: "✏️", url: "https://medium.com", color: "#000000" },
      { id: "slack", name: "Slack", nameUrdu: "سلیک", icon: "💼", url: "https://slack.com", color: "#4a154b" },
      { id: "teams", name: "Teams", nameUrdu: "ٹیمز", icon: "🤝", url: "https://teams.microsoft.com", color: "#6264a7" },
      { id: "zoom", name: "Zoom", nameUrdu: "زوم", icon: "📹", url: "https://zoom.us", color: "#2d8cff" },
      { id: "skype", name: "Skype", nameUrdu: "اسکائپ", icon: "📞", url: "https://web.skype.com", color: "#00aff0" },
    ],
  },
  {
    id: "general",
    name: "General",
    nameUrdu: "عمومی",
    icon: "⚡",
    color: "#ff8800",
    apps: [
      { id: "amazon2", name: "Amazon", nameUrdu: "امازون", icon: "🛒", url: "https://www.amazon.com", color: "#ff9900" },
      { id: "wiki", name: "Wikipedia", nameUrdu: "ویکیپیڈیا", icon: "📚", url: "https://www.wikipedia.org", color: "#000000" },
      { id: "gmail2", name: "Gmail", nameUrdu: "جی میل", icon: "📧", url: "https://mail.google.com", color: "#ea4335" },
      { id: "drive", name: "Google Drive", nameUrdu: "گوگل ڈرائیو", icon: "☁️", url: "https://drive.google.com", color: "#4285f4" },
      { id: "docs", name: "Google Docs", nameUrdu: "گوگل ڈاکس", icon: "📄", url: "https://docs.google.com", color: "#4285f4" },
      { id: "sheets", name: "Google Sheets", nameUrdu: "شیٹس", icon: "📊", url: "https://sheets.google.com", color: "#34a853" },
      { id: "calendar", name: "Calendar", nameUrdu: "کیلنڈر", icon: "📅", url: "https://calendar.google.com", color: "#4285f4" },
      { id: "weather", name: "Weather", nameUrdu: "موسم", icon: "🌤️", url: "https://weather.com", color: "#0099ff" },
      { id: "maps2", name: "Google Maps", nameUrdu: "گوگل نقشہ", icon: "🗺️", url: "https://maps.google.com", color: "#34a853" },
      { id: "translate2", name: "Translate", nameUrdu: "ترجمہ", icon: "🌐", url: "https://translate.google.com", color: "#4285f4" },
      { id: "github", name: "GitHub", nameUrdu: "گٹ ہب", icon: "💻", url: "https://github.com", color: "#333" },
      { id: "stackoverflow", name: "StackOverflow", nameUrdu: "اسٹیک اوور فلو", icon: "🔧", url: "https://stackoverflow.com", color: "#f48024" },
      { id: "udemy", name: "Udemy", nameUrdu: "یوڈیمی", icon: "🎓", url: "https://www.udemy.com", color: "#ec5252" },
      { id: "coursera", name: "Coursera", nameUrdu: "کورسیرا", icon: "📖", url: "https://www.coursera.org", color: "#0056d2" },
      { id: "canva", name: "Canva", nameUrdu: "کینوا", icon: "🎨", url: "https://www.canva.com", color: "#00c4cc" },
      { id: "figma", name: "Figma", nameUrdu: "فگما", icon: "✏️", url: "https://www.figma.com", color: "#f24e1e" },
      { id: "dropbox", name: "Dropbox", nameUrdu: "ڈراپ باکس", icon: "📦", url: "https://www.dropbox.com", color: "#0061ff" },
      { id: "paypal", name: "PayPal", nameUrdu: "پے پال", icon: "💳", url: "https://www.paypal.com", color: "#003087" },
      { id: "ebay", name: "eBay", nameUrdu: "ای بے", icon: "🏷️", url: "https://www.ebay.com", color: "#e43137" },
      { id: "daraz", name: "Daraz", nameUrdu: "دراز", icon: "🛍️", url: "https://www.daraz.pk", color: "#f57224" },
    ],
  },
];

// ─── Ticker Strips ──────────────────────────────────────────────────────────
export const TICKER_MESSAGES: TickerMessage[] = [
  {
    id: "top1",
    position: "top1",
    text: "🌙 EvEr SmArT BrOwSeR — Your intelligent companion for the digital world | Speed · Privacy · Style",
    textUrdu: "🌙 ذہین براؤزر — ڈیجیٹل دنیا کا آپ کا ذہین ساتھی | رفتار · رازداری · انداز",
  },
  {
    id: "top2",
    position: "top2",
    text: "✨ 16 Glassy Themes | Bilingual UI | 5 Content Hubs | PiP Player | Ad Blocker | Bookmark Manager",
    textUrdu: "✨ سولہ شیشہ نما تھیمز | دو لسانی انٹرفیس | پانچ مواد ہبز | پی آئی پی پلیئر | اشتہار بلاکر",
  },
  {
    id: "bottom1",
    position: "bottom1",
    text: "☪️ قرآن الکریم | سنت النبیﷺ | اوقات نماز | قبلہ کی سمت | دعائیں | اسلامی مواد",
    textUrdu: "☪️ The Holy Quran | Sunnah | Prayer Times | Qibla Direction | Duas | Islamic Content",
  },
  {
    id: "bottom2",
    position: "bottom2",
    text: "📰 Breaking News · Live Updates · Stay informed with global and local news from trusted sources",
    textUrdu: "📰 تازہ خبریں · لائیو اپڈیٹس · ملکی و بین الاقوامی خبریں",
  },
  {
    id: "bottom3",
    position: "bottom3",
    text: "🤖 AI Hub: ChatGPT · Gemini · Claude · Copilot · Perplexity · Midjourney · DALL-E · Grok",
    textUrdu: "🤖 اے آئی ہب: چیٹ جی پی ٹی · جیمنی · کلاڈ · کوپائلٹ · پرپلیکسٹی",
  },
  {
    id: "bottom4",
    position: "bottom4",
    text: "🌐 Social Hub: Facebook · Instagram · Twitter/X · TikTok · WhatsApp · Telegram · YouTube",
    textUrdu: "🌐 سوشل ہب: فیس بک · انسٹاگرام · ٹویٹر · ٹک ٹاک · واٹس ایپ · ٹیلیگرام",
  },
  {
    id: "bottom5",
    position: "bottom5",
    text: "⚡ General Hub: Amazon · Wikipedia · Gmail · Google Drive · GitHub · Udemy · Canva · Figma",
    textUrdu: "⚡ عمومی ہب: امازون · ویکیپیڈیا · جی میل · گوگل ڈرائیو · گٹ ہب · یوڈیمی",
  },
];

// ─── Personality Bar ────────────────────────────────────────────────────────
export const PERSONALITY_FIGURES: PersonalityFigure[] = [
  {
    id: "jinnah",
    name: "Quaid-e-Azam",
    nameUrdu: "قائداعظم",
    title: "Founder of Pakistan",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/Mohammed_Jinnah.jpg/400px-Mohammed_Jinnah.jpg",
    quote: "With faith, discipline and selfless devotion to duty, there is nothing worthwhile that you cannot achieve.",
  },
  {
    id: "iqbal",
    name: "Allama Iqbal",
    nameUrdu: "علامہ اقبال",
    title: "Poet of the East",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/33/Allama_Iqbal.jpg/400px-Allama_Iqbal.jpg",
    quote: "Raise yourself to such heights that God Himself asks of you: 'What is it that you desire?'",
  },
  {
    id: "aqkhan",
    name: "Aga Khan IV",
    nameUrdu: "آغا خان چہارم",
    title: "Imam of Ismaili Muslims",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b1/Shah_Karim_al-Husayni%2C_Aga_Khan_IV_%281965%29.jpg/400px-Shah_Karim_al-Husayni%2C_Aga_Khan_IV_%281965%29.jpg",
    quote: "The pursuit of excellence is not only a matter of intellectual rigor, but also of moral discipline.",
  },
];

export const ADMIN_PASSWORD_KEY = "esb_admin_password";
export const DEFAULT_ADMIN_PASSWORD = "1122";
